language: go

go:
  - "1.11.x"

env:
  global:
    - GO111MODULE=on
    - CODECOV_TOKEN="1fa035ad-f93a-4be5-9df6-a78c20f984e2"
    - TEST_DB_DSN='root@tcp(127.0.0.1:3306)/xm_test?charset=utf8mb4&parseTime=true&loc=Local'

services:
  - mysql

before_script:
  - mysql -e 'drop database if exists xm_test;'
  - mysql -e 'create database xm_test;'

install:
  - go mod download

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
